### ISSUE TITLE
Is this repository still valid?

### ISSUE THREAD

**Issue by packtman** [forcedotcom/force-dot-com-esapi#8]
Can someone please confirm if the repository is still maintained and valid for Apex?

Thanks.

**Comment by capeterson** [comment]
Yes. Myself and @voppon just volunteered to be the new maintainers of it. The content is still good, but it does admittedly have room for updates and improvements.

PRs will require a signed CLA and a review internally at Salesforce by product security if they make non-trivial changes. But yeah, it's alive.
