### ISSUE TITLE
Error while using in Apex class

### ISSUE THREAD

**Issue by PadmaRaghunathan** [forcedotcom/force-dot-com-esapi#9]
I have installed the unmanaged package from https://login.salesforce.com/packaging/installPackage.apexp?p0=04tE0000000R2Cg in one of my sandboxes. While using the library in my Apex class, it is throwing below error: 

![image](https://user-images.githubusercontent.com/44289590/47210262-239d0d00-d3b0-11e8-8903-cfa0f7dc65e5.png)

Can someone please guide?

**Comment by capeterson** [comment]
@PadmaRaghunathan probably too late to help, but the unmanaged version won't have the owasp namespace prefix, and would be referenced as just `ESAPI`. The namespace only exists on the managed version.
